spring:
    kafka:
      consumer:
        auto-offset-reset: latest
      bootstrap-servers: localhost:29092,localhost:29093,localhost:29094

kafka:
  topic:
    qrcode: qrcode-dev
server:
  port: 8085
